### ISSUE TITLE
race condition in test.test_writer.TestResultSink.test_send_chunk_size

### ISSUE THREAD

**Issue by david415** [TheTorProject/bwscanner#3]
```
(virtenv-bwscanner) user@subgraph:~/code/bwscanner$ trial test.test_writer.TestResultSink.test_send_chunk_size
test.test_writer
  TestResultSink
    test_send_chunk_size ...                                               [OK]

-------------------------------------------------------------------------------
Ran 1 tests in 0.032s

PASSED (successes=1)
(virtenv-bwscanner) user@subgraph:~/code/bwscanner$ trial test.test_writer.TestResultSink.test_send_chunk_size
test.test_writer
  TestResultSink
    test_send_chunk_size ...                                            [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/user/code/bwscanner/test/test_writer.py", line 52, in <lambda>
    lambda results: walk(self.tmpdir, validateoutput, None)
  File "/home/user/virtenv-bwscanner/lib/python2.7/posixpath.py", line 231, in walk
    func(arg, top, names)
  File "/home/user/code/bwscanner/test/test_writer.py", line 47, in validateoutput
    results = json.load(testfile)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
exceptions.ValueError: No JSON object could be decoded

test.test_writer.TestResultSink.test_send_chunk_size
-------------------------------------------------------------------------------
Ran 1 tests in 0.034s

FAILED (errors=1)
```

**Comment by david415** [comment]
i believe this test fails because in another thread the `send` method may have drained the buffer; meanwhile we call `end_flush` which immediately returns since the buffer is empty. we however do not find the json file because it hasn't been written to disk yet. test fail.

to fix this we need some sort of "wait" primitive such as a wait group or a mutex so we can cause `end_flush` to wait if the other thread is busy.

**Comment by david415** [comment]
fixed forever in commit https://github.com/TheTorProject/bwscanner/commit/03fc1a2d0c58e00c428a14abb4f79ed23576412b
