### ISSUE TITLE
txsocksx dependency is not compatible with Python 3

### ISSUE THREAD

**Issue by Tikam02** [TheTorProject/bwscanner#90]
root@hal:~/Projects/tor/bwscanner-develop# bwscan scan
Traceback (most recent call last):
  File "/root/anaconda3/bin/bwscan", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/root/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/root/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/root/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/root/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/root/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'txsocksx==1.15.0.2' distribution was not found and is required by bwscanner

root@hal:~/Projects/tor/bwscanner-develop# pip3 install txsocksx==1.15.0.2
Collecting txsocksx==1.15.0.2
  Using cached txsocksx-1.15.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-build-aa62oyed/txsocksx/.eggs/vcversioner-2.16.0.0-py3.6.egg
    error in txsocksx setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; 'int' object is not iterable
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aa62oyed/txsocksx/

**Comment by juga0** [comment]
Thanks @Tikam02 for the report.
The problem seems to be that you're running python (and pip) version 3. Unfortunately txsocksx dependency is not available for python 3.

**Comment by aagbsn** [comment]
@meejah mentioned on irc that there is python3 compatible code that can replace txsocksx that he wrote.
I think he might be referring to:
https://github.com/meejah/txtorcon/blob/master/txtorcon/socks.py
though it might be even easier to just use the web_agent method on the circ object. Thoughts?

**Comment by juga0** [comment]
Yes, we should use web_agent, as @DonnchaC and i started to do in this branch https://github.com/TheTorProject/bwscanner/commit/e0efe0af473a3b3152e60b6619617f074a077fca#diff-169c1db5ebb727a25ac9868e03e8bca5R162

**Comment by aagbsn** [comment]
https://github.com/TheTorProject/bwscanner/tree/use_txtorcon_web_agent
