### ISSUE TITLE
test_measurement.py fails

### ISSUE THREAD

**Issue by juga0** [TheTorProject/bwscanner#94]
Test fails running ``tox`` with ``./chutney start networks/basic-025``

    [ERROR]
    Traceback (most recent call last):
      File "/home/travis/build/juga0/bwscanner/test/test_measurement.py", line 68, in <lambda>
        scan.addCallback(lambda _: check_all_routers_measured(self.tmp))
      File "/home/travis/build/juga0/bwscanner/test/test_measurement.py", line 64, in check_all_routers_measured
        assert measured_relays == all_relays
    exceptions.AssertionError: 
    test.test_measurement.TestBwscan.test_scan_chutney

It might have to do with the algorithm used to choose the path [0]. Chutney creates less than 25 relays and the slice is 50.

[0] https://github.com/TheTorProject/bwscanner/blob/develop/bwscanner/circuit.py#L101

**Comment by aagbsn** [comment]
Is this reproducible every run? I tested branch develop at tip: cd023b228c36f63113f287cd35321718a238f842

**Comment by juga0** [comment]
Yes, it happens locally for me in every run using same branch and commit. 
It doesn't seem the case in travis thought.
