### ISSUE TITLE
Tests fail using chutney bwscanner configuration

### ISSUE THREAD

**Issue by juga0** [TheTorProject/bwscanner#97]
Running ``tox`` with ``./chutney start networks/bwscanner`` fails with different errors as #94:

    [FAIL]
    Traceback (most recent call last):
      File "/home/user/_my/code/tor-related/bwscanner/.tox/py27/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/home/user/_my/code/tor-related/bwscanner/.tox/py27/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/home/user/_my/code/tor-related/bwscanner/test/test_fetcher.py", line 79, in test_do_failing_request
        yield agent.request("GET", url)
      File "/home/user/_my/code/tor-related/bwscanner/.tox/py27/local/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 358, in __exit__
        self._expectedName, reason.getTraceback()),
    twisted.trial.unittest.FailTest: twisted.internet.error.ConnectionRefusedError raised instead of ConnectionRefused:
     Traceback (most recent call last):
      File "/home/user/_my/code/tor-related/bwscanner/.tox/py27/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
        _inlineCallbacks(r, g, deferred)
      File "/home/user/_my/code/tor-related/bwscanner/.tox/py27/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/home/user/_my/code/tor-related/bwscanner/.tox/py27/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/home/user/_my/code/tor-related/bwscanner/test/test_fetcher.py", line 79, in test_do_failing_request
        yield agent.request("GET", url)
    --- <exception caught here> ---
      File "/home/user/_my/code/tor-related/bwscanner/test/test_fetcher.py", line 79, in test_do_failing_request
        yield agent.request("GET", url)
    twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.

**Comment by aagbsn** [comment]
which branch is this? Is there a networks/bwscanner chutney configuration added somewhere?

**Comment by juga0** [comment]
> which branch is this?

develop, using virtualenv and running tests as explained in README

> Is there a networks/bwscanner chutney configuration added somewhere?

Yes, added in chutney: https://trac.torproject.org/projects/tor/ticket/25228#comment:6 -> https://gitweb.torproject.org/chutney.git/commit/?id=f5745c80ad6ef6072f42b56c9b6ab3e54a98355f

**Comment by juga0** [comment]
Also, ``./chutney start networks/bwscanner`` fails with errors as:

    Starting nodes
    Couldn't launch test000a

TODO: as suggested by @teor2345, look at chutney/tools/warnings.sh, https://trac.torproject.org/projects/tor/ticket/16386 and https://trac.torproject.org/projects/tor/ticket/17036
